// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Class is the predicate function for class builders.
type Class func(*sql.Selector)

// Homework is the predicate function for homework builders.
type Homework func(*sql.Selector)

// Notice is the predicate function for notice builders.
type Notice func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserHomeWork is the predicate function for userhomework builders.
type UserHomeWork func(*sql.Selector)
