// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountColumns holds the columns for the "account" table.
	AccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "user_id", Type: field.TypeUint64, Nullable: true},
		{Name: "account", Type: field.TypeString, Nullable: true},
		{Name: "password", Type: field.TypeString, Nullable: true},
		{Name: "permission", Type: field.TypeUint8, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// AccountTable holds the schema information for the "account" table.
	AccountTable = &schema.Table{
		Name:       "account",
		Columns:    AccountColumns,
		PrimaryKey: []*schema.Column{AccountColumns[0]},
	}
	// ClassColumns holds the columns for the "class" table.
	ClassColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "extra", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// ClassTable holds the schema information for the "class" table.
	ClassTable = &schema.Table{
		Name:       "class",
		Columns:    ClassColumns,
		PrimaryKey: []*schema.Column{ClassColumns[0]},
	}
	// HomeworkColumns holds the columns for the "homework" table.
	HomeworkColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "pics", Type: field.TypeJSON, Nullable: true},
		{Name: "class_id", Type: field.TypeUint8, Nullable: true},
		{Name: "class_name", Type: field.TypeString, Nullable: true},
		{Name: "teacher_id", Type: field.TypeUint8, Nullable: true},
		{Name: "extra", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// HomeworkTable holds the schema information for the "homework" table.
	HomeworkTable = &schema.Table{
		Name:       "homework",
		Columns:    HomeworkColumns,
		PrimaryKey: []*schema.Column{HomeworkColumns[0]},
	}
	// NoticeColumns holds the columns for the "notice" table.
	NoticeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "level", Type: field.TypeUint8, Nullable: true},
		{Name: "extra", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// NoticeTable holds the schema information for the "notice" table.
	NoticeTable = &schema.Table{
		Name:       "notice",
		Columns:    NoticeColumns,
		PrimaryKey: []*schema.Column{NoticeColumns[0]},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "nickname", Type: field.TypeString, Nullable: true},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "mobile", Type: field.TypeString, Nullable: true},
		{Name: "extra", Type: field.TypeString, Nullable: true},
		{Name: "class_id", Type: field.TypeUint8, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// StuHomeworkColumns holds the columns for the "stu_homework" table.
	StuHomeworkColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "homework_id", Type: field.TypeUint64, Nullable: true},
		{Name: "user_id", Type: field.TypeUint64, Nullable: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "pics", Type: field.TypeJSON, Nullable: true},
		{Name: "extra", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// StuHomeworkTable holds the schema information for the "stu_homework" table.
	StuHomeworkTable = &schema.Table{
		Name:       "stu_homework",
		Columns:    StuHomeworkColumns,
		PrimaryKey: []*schema.Column{StuHomeworkColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountTable,
		ClassTable,
		HomeworkTable,
		NoticeTable,
		UserTable,
		StuHomeworkTable,
	}
)

func init() {
	AccountTable.Annotation = &entsql.Annotation{
		Table: "account",
	}
	ClassTable.Annotation = &entsql.Annotation{
		Table: "class",
	}
	HomeworkTable.Annotation = &entsql.Annotation{
		Table: "homework",
	}
	NoticeTable.Annotation = &entsql.Annotation{
		Table: "notice",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
	StuHomeworkTable.Annotation = &entsql.Annotation{
		Table: "stu_homework",
	}
}
