// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"family-joint-school/model"
	"family-joint-school/mysql/ent/homework"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HomeworkCreate is the builder for creating a Homework entity.
type HomeworkCreate struct {
	config
	mutation *HomeworkMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (hc *HomeworkCreate) SetTitle(s string) *HomeworkCreate {
	hc.mutation.SetTitle(s)
	return hc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (hc *HomeworkCreate) SetNillableTitle(s *string) *HomeworkCreate {
	if s != nil {
		hc.SetTitle(*s)
	}
	return hc
}

// SetContent sets the "content" field.
func (hc *HomeworkCreate) SetContent(s string) *HomeworkCreate {
	hc.mutation.SetContent(s)
	return hc
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (hc *HomeworkCreate) SetNillableContent(s *string) *HomeworkCreate {
	if s != nil {
		hc.SetContent(*s)
	}
	return hc
}

// SetPics sets the "pics" field.
func (hc *HomeworkCreate) SetPics(m []model.Pic) *HomeworkCreate {
	hc.mutation.SetPics(m)
	return hc
}

// SetClassID sets the "class_id" field.
func (hc *HomeworkCreate) SetClassID(u uint8) *HomeworkCreate {
	hc.mutation.SetClassID(u)
	return hc
}

// SetNillableClassID sets the "class_id" field if the given value is not nil.
func (hc *HomeworkCreate) SetNillableClassID(u *uint8) *HomeworkCreate {
	if u != nil {
		hc.SetClassID(*u)
	}
	return hc
}

// SetClassName sets the "class_name" field.
func (hc *HomeworkCreate) SetClassName(s string) *HomeworkCreate {
	hc.mutation.SetClassName(s)
	return hc
}

// SetNillableClassName sets the "class_name" field if the given value is not nil.
func (hc *HomeworkCreate) SetNillableClassName(s *string) *HomeworkCreate {
	if s != nil {
		hc.SetClassName(*s)
	}
	return hc
}

// SetTeacherID sets the "teacher_id" field.
func (hc *HomeworkCreate) SetTeacherID(u uint8) *HomeworkCreate {
	hc.mutation.SetTeacherID(u)
	return hc
}

// SetNillableTeacherID sets the "teacher_id" field if the given value is not nil.
func (hc *HomeworkCreate) SetNillableTeacherID(u *uint8) *HomeworkCreate {
	if u != nil {
		hc.SetTeacherID(*u)
	}
	return hc
}

// SetExtra sets the "extra" field.
func (hc *HomeworkCreate) SetExtra(s string) *HomeworkCreate {
	hc.mutation.SetExtra(s)
	return hc
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (hc *HomeworkCreate) SetNillableExtra(s *string) *HomeworkCreate {
	if s != nil {
		hc.SetExtra(*s)
	}
	return hc
}

// SetCreatedAt sets the "created_at" field.
func (hc *HomeworkCreate) SetCreatedAt(t time.Time) *HomeworkCreate {
	hc.mutation.SetCreatedAt(t)
	return hc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (hc *HomeworkCreate) SetNillableCreatedAt(t *time.Time) *HomeworkCreate {
	if t != nil {
		hc.SetCreatedAt(*t)
	}
	return hc
}

// SetUpdatedAt sets the "updated_at" field.
func (hc *HomeworkCreate) SetUpdatedAt(t time.Time) *HomeworkCreate {
	hc.mutation.SetUpdatedAt(t)
	return hc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (hc *HomeworkCreate) SetNillableUpdatedAt(t *time.Time) *HomeworkCreate {
	if t != nil {
		hc.SetUpdatedAt(*t)
	}
	return hc
}

// SetID sets the "id" field.
func (hc *HomeworkCreate) SetID(u uint64) *HomeworkCreate {
	hc.mutation.SetID(u)
	return hc
}

// Mutation returns the HomeworkMutation object of the builder.
func (hc *HomeworkCreate) Mutation() *HomeworkMutation {
	return hc.mutation
}

// Save creates the Homework in the database.
func (hc *HomeworkCreate) Save(ctx context.Context) (*Homework, error) {
	var (
		err  error
		node *Homework
	)
	hc.defaults()
	if len(hc.hooks) == 0 {
		if err = hc.check(); err != nil {
			return nil, err
		}
		node, err = hc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HomeworkMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = hc.check(); err != nil {
				return nil, err
			}
			hc.mutation = mutation
			if node, err = hc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(hc.hooks) - 1; i >= 0; i-- {
			if hc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = hc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, hc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Homework)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from HomeworkMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HomeworkCreate) SaveX(ctx context.Context) *Homework {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HomeworkCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HomeworkCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hc *HomeworkCreate) defaults() {
	if _, ok := hc.mutation.CreatedAt(); !ok {
		v := homework.DefaultCreatedAt()
		hc.mutation.SetCreatedAt(v)
	}
	if _, ok := hc.mutation.UpdatedAt(); !ok {
		v := homework.DefaultUpdatedAt()
		hc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HomeworkCreate) check() error {
	return nil
}

func (hc *HomeworkCreate) sqlSave(ctx context.Context) (*Homework, error) {
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	return _node, nil
}

func (hc *HomeworkCreate) createSpec() (*Homework, *sqlgraph.CreateSpec) {
	var (
		_node = &Homework{config: hc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: homework.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: homework.FieldID,
			},
		}
	)
	if id, ok := hc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := hc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: homework.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := hc.mutation.Content(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: homework.FieldContent,
		})
		_node.Content = value
	}
	if value, ok := hc.mutation.Pics(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: homework.FieldPics,
		})
		_node.Pics = value
	}
	if value, ok := hc.mutation.ClassID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: homework.FieldClassID,
		})
		_node.ClassID = value
	}
	if value, ok := hc.mutation.ClassName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: homework.FieldClassName,
		})
		_node.ClassName = value
	}
	if value, ok := hc.mutation.TeacherID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: homework.FieldTeacherID,
		})
		_node.TeacherID = value
	}
	if value, ok := hc.mutation.Extra(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: homework.FieldExtra,
		})
		_node.Extra = value
	}
	if value, ok := hc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: homework.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := hc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: homework.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// HomeworkCreateBulk is the builder for creating many Homework entities in bulk.
type HomeworkCreateBulk struct {
	config
	builders []*HomeworkCreate
}

// Save creates the Homework entities in the database.
func (hcb *HomeworkCreateBulk) Save(ctx context.Context) ([]*Homework, error) {
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Homework, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HomeworkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HomeworkCreateBulk) SaveX(ctx context.Context) []*Homework {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HomeworkCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HomeworkCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
