// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"family-joint-school/mysql/ent/notice"
	"family-joint-school/mysql/ent/predicate"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NoticeUpdate is the builder for updating Notice entities.
type NoticeUpdate struct {
	config
	hooks    []Hook
	mutation *NoticeMutation
}

// Where appends a list predicates to the NoticeUpdate builder.
func (nu *NoticeUpdate) Where(ps ...predicate.Notice) *NoticeUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetTitle sets the "title" field.
func (nu *NoticeUpdate) SetTitle(s string) *NoticeUpdate {
	nu.mutation.SetTitle(s)
	return nu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (nu *NoticeUpdate) SetNillableTitle(s *string) *NoticeUpdate {
	if s != nil {
		nu.SetTitle(*s)
	}
	return nu
}

// ClearTitle clears the value of the "title" field.
func (nu *NoticeUpdate) ClearTitle() *NoticeUpdate {
	nu.mutation.ClearTitle()
	return nu
}

// SetContent sets the "content" field.
func (nu *NoticeUpdate) SetContent(s string) *NoticeUpdate {
	nu.mutation.SetContent(s)
	return nu
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (nu *NoticeUpdate) SetNillableContent(s *string) *NoticeUpdate {
	if s != nil {
		nu.SetContent(*s)
	}
	return nu
}

// ClearContent clears the value of the "content" field.
func (nu *NoticeUpdate) ClearContent() *NoticeUpdate {
	nu.mutation.ClearContent()
	return nu
}

// SetLevel sets the "level" field.
func (nu *NoticeUpdate) SetLevel(u uint8) *NoticeUpdate {
	nu.mutation.ResetLevel()
	nu.mutation.SetLevel(u)
	return nu
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (nu *NoticeUpdate) SetNillableLevel(u *uint8) *NoticeUpdate {
	if u != nil {
		nu.SetLevel(*u)
	}
	return nu
}

// AddLevel adds u to the "level" field.
func (nu *NoticeUpdate) AddLevel(u int8) *NoticeUpdate {
	nu.mutation.AddLevel(u)
	return nu
}

// ClearLevel clears the value of the "level" field.
func (nu *NoticeUpdate) ClearLevel() *NoticeUpdate {
	nu.mutation.ClearLevel()
	return nu
}

// SetExtra sets the "extra" field.
func (nu *NoticeUpdate) SetExtra(s string) *NoticeUpdate {
	nu.mutation.SetExtra(s)
	return nu
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (nu *NoticeUpdate) SetNillableExtra(s *string) *NoticeUpdate {
	if s != nil {
		nu.SetExtra(*s)
	}
	return nu
}

// ClearExtra clears the value of the "extra" field.
func (nu *NoticeUpdate) ClearExtra() *NoticeUpdate {
	nu.mutation.ClearExtra()
	return nu
}

// SetCreatedAt sets the "created_at" field.
func (nu *NoticeUpdate) SetCreatedAt(t time.Time) *NoticeUpdate {
	nu.mutation.SetCreatedAt(t)
	return nu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nu *NoticeUpdate) SetNillableCreatedAt(t *time.Time) *NoticeUpdate {
	if t != nil {
		nu.SetCreatedAt(*t)
	}
	return nu
}

// ClearCreatedAt clears the value of the "created_at" field.
func (nu *NoticeUpdate) ClearCreatedAt() *NoticeUpdate {
	nu.mutation.ClearCreatedAt()
	return nu
}

// SetUpdatedAt sets the "updated_at" field.
func (nu *NoticeUpdate) SetUpdatedAt(t time.Time) *NoticeUpdate {
	nu.mutation.SetUpdatedAt(t)
	return nu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (nu *NoticeUpdate) ClearUpdatedAt() *NoticeUpdate {
	nu.mutation.ClearUpdatedAt()
	return nu
}

// Mutation returns the NoticeMutation object of the builder.
func (nu *NoticeUpdate) Mutation() *NoticeMutation {
	return nu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NoticeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	nu.defaults()
	if len(nu.hooks) == 0 {
		affected, err = nu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NoticeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nu.mutation = mutation
			affected, err = nu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nu.hooks) - 1; i >= 0; i-- {
			if nu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NoticeUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NoticeUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NoticeUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nu *NoticeUpdate) defaults() {
	if _, ok := nu.mutation.UpdatedAt(); !ok && !nu.mutation.UpdatedAtCleared() {
		v := notice.UpdateDefaultUpdatedAt()
		nu.mutation.SetUpdatedAt(v)
	}
}

func (nu *NoticeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   notice.Table,
			Columns: notice.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: notice.FieldID,
			},
		},
	}
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldTitle,
		})
	}
	if nu.mutation.TitleCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notice.FieldTitle,
		})
	}
	if value, ok := nu.mutation.Content(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldContent,
		})
	}
	if nu.mutation.ContentCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notice.FieldContent,
		})
	}
	if value, ok := nu.mutation.Level(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: notice.FieldLevel,
		})
	}
	if value, ok := nu.mutation.AddedLevel(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: notice.FieldLevel,
		})
	}
	if nu.mutation.LevelCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Column: notice.FieldLevel,
		})
	}
	if value, ok := nu.mutation.Extra(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldExtra,
		})
	}
	if nu.mutation.ExtraCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notice.FieldExtra,
		})
	}
	if value, ok := nu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notice.FieldCreatedAt,
		})
	}
	if nu.mutation.CreatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: notice.FieldCreatedAt,
		})
	}
	if value, ok := nu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notice.FieldUpdatedAt,
		})
	}
	if nu.mutation.UpdatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: notice.FieldUpdatedAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// NoticeUpdateOne is the builder for updating a single Notice entity.
type NoticeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NoticeMutation
}

// SetTitle sets the "title" field.
func (nuo *NoticeUpdateOne) SetTitle(s string) *NoticeUpdateOne {
	nuo.mutation.SetTitle(s)
	return nuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (nuo *NoticeUpdateOne) SetNillableTitle(s *string) *NoticeUpdateOne {
	if s != nil {
		nuo.SetTitle(*s)
	}
	return nuo
}

// ClearTitle clears the value of the "title" field.
func (nuo *NoticeUpdateOne) ClearTitle() *NoticeUpdateOne {
	nuo.mutation.ClearTitle()
	return nuo
}

// SetContent sets the "content" field.
func (nuo *NoticeUpdateOne) SetContent(s string) *NoticeUpdateOne {
	nuo.mutation.SetContent(s)
	return nuo
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (nuo *NoticeUpdateOne) SetNillableContent(s *string) *NoticeUpdateOne {
	if s != nil {
		nuo.SetContent(*s)
	}
	return nuo
}

// ClearContent clears the value of the "content" field.
func (nuo *NoticeUpdateOne) ClearContent() *NoticeUpdateOne {
	nuo.mutation.ClearContent()
	return nuo
}

// SetLevel sets the "level" field.
func (nuo *NoticeUpdateOne) SetLevel(u uint8) *NoticeUpdateOne {
	nuo.mutation.ResetLevel()
	nuo.mutation.SetLevel(u)
	return nuo
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (nuo *NoticeUpdateOne) SetNillableLevel(u *uint8) *NoticeUpdateOne {
	if u != nil {
		nuo.SetLevel(*u)
	}
	return nuo
}

// AddLevel adds u to the "level" field.
func (nuo *NoticeUpdateOne) AddLevel(u int8) *NoticeUpdateOne {
	nuo.mutation.AddLevel(u)
	return nuo
}

// ClearLevel clears the value of the "level" field.
func (nuo *NoticeUpdateOne) ClearLevel() *NoticeUpdateOne {
	nuo.mutation.ClearLevel()
	return nuo
}

// SetExtra sets the "extra" field.
func (nuo *NoticeUpdateOne) SetExtra(s string) *NoticeUpdateOne {
	nuo.mutation.SetExtra(s)
	return nuo
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (nuo *NoticeUpdateOne) SetNillableExtra(s *string) *NoticeUpdateOne {
	if s != nil {
		nuo.SetExtra(*s)
	}
	return nuo
}

// ClearExtra clears the value of the "extra" field.
func (nuo *NoticeUpdateOne) ClearExtra() *NoticeUpdateOne {
	nuo.mutation.ClearExtra()
	return nuo
}

// SetCreatedAt sets the "created_at" field.
func (nuo *NoticeUpdateOne) SetCreatedAt(t time.Time) *NoticeUpdateOne {
	nuo.mutation.SetCreatedAt(t)
	return nuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nuo *NoticeUpdateOne) SetNillableCreatedAt(t *time.Time) *NoticeUpdateOne {
	if t != nil {
		nuo.SetCreatedAt(*t)
	}
	return nuo
}

// ClearCreatedAt clears the value of the "created_at" field.
func (nuo *NoticeUpdateOne) ClearCreatedAt() *NoticeUpdateOne {
	nuo.mutation.ClearCreatedAt()
	return nuo
}

// SetUpdatedAt sets the "updated_at" field.
func (nuo *NoticeUpdateOne) SetUpdatedAt(t time.Time) *NoticeUpdateOne {
	nuo.mutation.SetUpdatedAt(t)
	return nuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (nuo *NoticeUpdateOne) ClearUpdatedAt() *NoticeUpdateOne {
	nuo.mutation.ClearUpdatedAt()
	return nuo
}

// Mutation returns the NoticeMutation object of the builder.
func (nuo *NoticeUpdateOne) Mutation() *NoticeMutation {
	return nuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NoticeUpdateOne) Select(field string, fields ...string) *NoticeUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Notice entity.
func (nuo *NoticeUpdateOne) Save(ctx context.Context) (*Notice, error) {
	var (
		err  error
		node *Notice
	)
	nuo.defaults()
	if len(nuo.hooks) == 0 {
		node, err = nuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NoticeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nuo.mutation = mutation
			node, err = nuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(nuo.hooks) - 1; i >= 0; i-- {
			if nuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, nuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Notice)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from NoticeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NoticeUpdateOne) SaveX(ctx context.Context) *Notice {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NoticeUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NoticeUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nuo *NoticeUpdateOne) defaults() {
	if _, ok := nuo.mutation.UpdatedAt(); !ok && !nuo.mutation.UpdatedAtCleared() {
		v := notice.UpdateDefaultUpdatedAt()
		nuo.mutation.SetUpdatedAt(v)
	}
}

func (nuo *NoticeUpdateOne) sqlSave(ctx context.Context) (_node *Notice, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   notice.Table,
			Columns: notice.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: notice.FieldID,
			},
		},
	}
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notice.FieldID)
		for _, f := range fields {
			if !notice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldTitle,
		})
	}
	if nuo.mutation.TitleCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notice.FieldTitle,
		})
	}
	if value, ok := nuo.mutation.Content(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldContent,
		})
	}
	if nuo.mutation.ContentCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notice.FieldContent,
		})
	}
	if value, ok := nuo.mutation.Level(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: notice.FieldLevel,
		})
	}
	if value, ok := nuo.mutation.AddedLevel(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: notice.FieldLevel,
		})
	}
	if nuo.mutation.LevelCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Column: notice.FieldLevel,
		})
	}
	if value, ok := nuo.mutation.Extra(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldExtra,
		})
	}
	if nuo.mutation.ExtraCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: notice.FieldExtra,
		})
	}
	if value, ok := nuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notice.FieldCreatedAt,
		})
	}
	if nuo.mutation.CreatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: notice.FieldCreatedAt,
		})
	}
	if value, ok := nuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notice.FieldUpdatedAt,
		})
	}
	if nuo.mutation.UpdatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: notice.FieldUpdatedAt,
		})
	}
	_node = &Notice{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
