// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"family-joint-school/mysql/ent/notice"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NoticeCreate is the builder for creating a Notice entity.
type NoticeCreate struct {
	config
	mutation *NoticeMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (nc *NoticeCreate) SetTitle(s string) *NoticeCreate {
	nc.mutation.SetTitle(s)
	return nc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (nc *NoticeCreate) SetNillableTitle(s *string) *NoticeCreate {
	if s != nil {
		nc.SetTitle(*s)
	}
	return nc
}

// SetContent sets the "content" field.
func (nc *NoticeCreate) SetContent(s string) *NoticeCreate {
	nc.mutation.SetContent(s)
	return nc
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (nc *NoticeCreate) SetNillableContent(s *string) *NoticeCreate {
	if s != nil {
		nc.SetContent(*s)
	}
	return nc
}

// SetLevel sets the "level" field.
func (nc *NoticeCreate) SetLevel(u uint8) *NoticeCreate {
	nc.mutation.SetLevel(u)
	return nc
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (nc *NoticeCreate) SetNillableLevel(u *uint8) *NoticeCreate {
	if u != nil {
		nc.SetLevel(*u)
	}
	return nc
}

// SetExtra sets the "extra" field.
func (nc *NoticeCreate) SetExtra(s string) *NoticeCreate {
	nc.mutation.SetExtra(s)
	return nc
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (nc *NoticeCreate) SetNillableExtra(s *string) *NoticeCreate {
	if s != nil {
		nc.SetExtra(*s)
	}
	return nc
}

// SetCreatedAt sets the "created_at" field.
func (nc *NoticeCreate) SetCreatedAt(t time.Time) *NoticeCreate {
	nc.mutation.SetCreatedAt(t)
	return nc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nc *NoticeCreate) SetNillableCreatedAt(t *time.Time) *NoticeCreate {
	if t != nil {
		nc.SetCreatedAt(*t)
	}
	return nc
}

// SetUpdatedAt sets the "updated_at" field.
func (nc *NoticeCreate) SetUpdatedAt(t time.Time) *NoticeCreate {
	nc.mutation.SetUpdatedAt(t)
	return nc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (nc *NoticeCreate) SetNillableUpdatedAt(t *time.Time) *NoticeCreate {
	if t != nil {
		nc.SetUpdatedAt(*t)
	}
	return nc
}

// SetID sets the "id" field.
func (nc *NoticeCreate) SetID(u uint64) *NoticeCreate {
	nc.mutation.SetID(u)
	return nc
}

// Mutation returns the NoticeMutation object of the builder.
func (nc *NoticeCreate) Mutation() *NoticeMutation {
	return nc.mutation
}

// Save creates the Notice in the database.
func (nc *NoticeCreate) Save(ctx context.Context) (*Notice, error) {
	var (
		err  error
		node *Notice
	)
	nc.defaults()
	if len(nc.hooks) == 0 {
		if err = nc.check(); err != nil {
			return nil, err
		}
		node, err = nc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NoticeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nc.check(); err != nil {
				return nil, err
			}
			nc.mutation = mutation
			if node, err = nc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(nc.hooks) - 1; i >= 0; i-- {
			if nc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, nc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Notice)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from NoticeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NoticeCreate) SaveX(ctx context.Context) *Notice {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nc *NoticeCreate) Exec(ctx context.Context) error {
	_, err := nc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nc *NoticeCreate) ExecX(ctx context.Context) {
	if err := nc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nc *NoticeCreate) defaults() {
	if _, ok := nc.mutation.CreatedAt(); !ok {
		v := notice.DefaultCreatedAt()
		nc.mutation.SetCreatedAt(v)
	}
	if _, ok := nc.mutation.UpdatedAt(); !ok {
		v := notice.DefaultUpdatedAt()
		nc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nc *NoticeCreate) check() error {
	return nil
}

func (nc *NoticeCreate) sqlSave(ctx context.Context) (*Notice, error) {
	_node, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	return _node, nil
}

func (nc *NoticeCreate) createSpec() (*Notice, *sqlgraph.CreateSpec) {
	var (
		_node = &Notice{config: nc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: notice.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: notice.FieldID,
			},
		}
	)
	if id, ok := nc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := nc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := nc.mutation.Content(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldContent,
		})
		_node.Content = value
	}
	if value, ok := nc.mutation.Level(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: notice.FieldLevel,
		})
		_node.Level = value
	}
	if value, ok := nc.mutation.Extra(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notice.FieldExtra,
		})
		_node.Extra = value
	}
	if value, ok := nc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notice.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := nc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notice.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// NoticeCreateBulk is the builder for creating many Notice entities in bulk.
type NoticeCreateBulk struct {
	config
	builders []*NoticeCreate
}

// Save creates the Notice entities in the database.
func (ncb *NoticeCreateBulk) Save(ctx context.Context) ([]*Notice, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ncb.builders))
	nodes := make([]*Notice, len(ncb.builders))
	mutators := make([]Mutator, len(ncb.builders))
	for i := range ncb.builders {
		func(i int, root context.Context) {
			builder := ncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NoticeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ncb *NoticeCreateBulk) SaveX(ctx context.Context) []*Notice {
	v, err := ncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncb *NoticeCreateBulk) Exec(ctx context.Context) error {
	_, err := ncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncb *NoticeCreateBulk) ExecX(ctx context.Context) {
	if err := ncb.Exec(ctx); err != nil {
		panic(err)
	}
}
