// Code generated by ent, DO NOT EDIT.

package ent

import (
	"family-joint-school/mysql/ent/account"
	"family-joint-school/mysql/ent/class"
	"family-joint-school/mysql/ent/homework"
	"family-joint-school/mysql/ent/notice"
	"family-joint-school/mysql/ent/schema"
	"family-joint-school/mysql/ent/user"
	"family-joint-school/mysql/ent/userhomework"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[5].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[6].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	classFields := schema.Class{}.Fields()
	_ = classFields
	// classDescCreatedAt is the schema descriptor for created_at field.
	classDescCreatedAt := classFields[3].Descriptor()
	// class.DefaultCreatedAt holds the default value on creation for the created_at field.
	class.DefaultCreatedAt = classDescCreatedAt.Default.(func() time.Time)
	// classDescUpdatedAt is the schema descriptor for updated_at field.
	classDescUpdatedAt := classFields[4].Descriptor()
	// class.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	class.DefaultUpdatedAt = classDescUpdatedAt.Default.(func() time.Time)
	// class.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	class.UpdateDefaultUpdatedAt = classDescUpdatedAt.UpdateDefault.(func() time.Time)
	homeworkFields := schema.Homework{}.Fields()
	_ = homeworkFields
	// homeworkDescCreatedAt is the schema descriptor for created_at field.
	homeworkDescCreatedAt := homeworkFields[8].Descriptor()
	// homework.DefaultCreatedAt holds the default value on creation for the created_at field.
	homework.DefaultCreatedAt = homeworkDescCreatedAt.Default.(func() time.Time)
	// homeworkDescUpdatedAt is the schema descriptor for updated_at field.
	homeworkDescUpdatedAt := homeworkFields[9].Descriptor()
	// homework.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	homework.DefaultUpdatedAt = homeworkDescUpdatedAt.Default.(func() time.Time)
	// homework.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	homework.UpdateDefaultUpdatedAt = homeworkDescUpdatedAt.UpdateDefault.(func() time.Time)
	noticeFields := schema.Notice{}.Fields()
	_ = noticeFields
	// noticeDescCreatedAt is the schema descriptor for created_at field.
	noticeDescCreatedAt := noticeFields[5].Descriptor()
	// notice.DefaultCreatedAt holds the default value on creation for the created_at field.
	notice.DefaultCreatedAt = noticeDescCreatedAt.Default.(func() time.Time)
	// noticeDescUpdatedAt is the schema descriptor for updated_at field.
	noticeDescUpdatedAt := noticeFields[6].Descriptor()
	// notice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notice.DefaultUpdatedAt = noticeDescUpdatedAt.Default.(func() time.Time)
	// notice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notice.UpdateDefaultUpdatedAt = noticeDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[7].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	userhomeworkFields := schema.UserHomeWork{}.Fields()
	_ = userhomeworkFields
	// userhomeworkDescCreatedAt is the schema descriptor for created_at field.
	userhomeworkDescCreatedAt := userhomeworkFields[7].Descriptor()
	// userhomework.DefaultCreatedAt holds the default value on creation for the created_at field.
	userhomework.DefaultCreatedAt = userhomeworkDescCreatedAt.Default.(func() time.Time)
	// userhomeworkDescUpdatedAt is the schema descriptor for updated_at field.
	userhomeworkDescUpdatedAt := userhomeworkFields[8].Descriptor()
	// userhomework.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userhomework.DefaultUpdatedAt = userhomeworkDescUpdatedAt.Default.(func() time.Time)
	// userhomework.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userhomework.UpdateDefaultUpdatedAt = userhomeworkDescUpdatedAt.UpdateDefault.(func() time.Time)
}
