// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"family-joint-school/mysql/ent/predicate"
	"family-joint-school/mysql/ent/userhomework"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserHomeWorkDelete is the builder for deleting a UserHomeWork entity.
type UserHomeWorkDelete struct {
	config
	hooks    []Hook
	mutation *UserHomeWorkMutation
}

// Where appends a list predicates to the UserHomeWorkDelete builder.
func (uhwd *UserHomeWorkDelete) Where(ps ...predicate.UserHomeWork) *UserHomeWorkDelete {
	uhwd.mutation.Where(ps...)
	return uhwd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uhwd *UserHomeWorkDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uhwd.hooks) == 0 {
		affected, err = uhwd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserHomeWorkMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uhwd.mutation = mutation
			affected, err = uhwd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uhwd.hooks) - 1; i >= 0; i-- {
			if uhwd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uhwd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uhwd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (uhwd *UserHomeWorkDelete) ExecX(ctx context.Context) int {
	n, err := uhwd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uhwd *UserHomeWorkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: userhomework.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: userhomework.FieldID,
			},
		},
	}
	if ps := uhwd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uhwd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// UserHomeWorkDeleteOne is the builder for deleting a single UserHomeWork entity.
type UserHomeWorkDeleteOne struct {
	uhwd *UserHomeWorkDelete
}

// Exec executes the deletion query.
func (uhwdo *UserHomeWorkDeleteOne) Exec(ctx context.Context) error {
	n, err := uhwdo.uhwd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userhomework.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uhwdo *UserHomeWorkDeleteOne) ExecX(ctx context.Context) {
	uhwdo.uhwd.ExecX(ctx)
}
