// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"family-joint-school/model"
	"family-joint-school/mysql/ent/userhomework"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserHomeWorkCreate is the builder for creating a UserHomeWork entity.
type UserHomeWorkCreate struct {
	config
	mutation *UserHomeWorkMutation
	hooks    []Hook
}

// SetHomeworkID sets the "homework_id" field.
func (uhwc *UserHomeWorkCreate) SetHomeworkID(u uint64) *UserHomeWorkCreate {
	uhwc.mutation.SetHomeworkID(u)
	return uhwc
}

// SetNillableHomeworkID sets the "homework_id" field if the given value is not nil.
func (uhwc *UserHomeWorkCreate) SetNillableHomeworkID(u *uint64) *UserHomeWorkCreate {
	if u != nil {
		uhwc.SetHomeworkID(*u)
	}
	return uhwc
}

// SetUserID sets the "user_id" field.
func (uhwc *UserHomeWorkCreate) SetUserID(u uint64) *UserHomeWorkCreate {
	uhwc.mutation.SetUserID(u)
	return uhwc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (uhwc *UserHomeWorkCreate) SetNillableUserID(u *uint64) *UserHomeWorkCreate {
	if u != nil {
		uhwc.SetUserID(*u)
	}
	return uhwc
}

// SetTitle sets the "title" field.
func (uhwc *UserHomeWorkCreate) SetTitle(s string) *UserHomeWorkCreate {
	uhwc.mutation.SetTitle(s)
	return uhwc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (uhwc *UserHomeWorkCreate) SetNillableTitle(s *string) *UserHomeWorkCreate {
	if s != nil {
		uhwc.SetTitle(*s)
	}
	return uhwc
}

// SetContent sets the "content" field.
func (uhwc *UserHomeWorkCreate) SetContent(s string) *UserHomeWorkCreate {
	uhwc.mutation.SetContent(s)
	return uhwc
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (uhwc *UserHomeWorkCreate) SetNillableContent(s *string) *UserHomeWorkCreate {
	if s != nil {
		uhwc.SetContent(*s)
	}
	return uhwc
}

// SetPics sets the "pics" field.
func (uhwc *UserHomeWorkCreate) SetPics(m []model.Pic) *UserHomeWorkCreate {
	uhwc.mutation.SetPics(m)
	return uhwc
}

// SetExtra sets the "extra" field.
func (uhwc *UserHomeWorkCreate) SetExtra(s string) *UserHomeWorkCreate {
	uhwc.mutation.SetExtra(s)
	return uhwc
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (uhwc *UserHomeWorkCreate) SetNillableExtra(s *string) *UserHomeWorkCreate {
	if s != nil {
		uhwc.SetExtra(*s)
	}
	return uhwc
}

// SetCreatedAt sets the "created_at" field.
func (uhwc *UserHomeWorkCreate) SetCreatedAt(t time.Time) *UserHomeWorkCreate {
	uhwc.mutation.SetCreatedAt(t)
	return uhwc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uhwc *UserHomeWorkCreate) SetNillableCreatedAt(t *time.Time) *UserHomeWorkCreate {
	if t != nil {
		uhwc.SetCreatedAt(*t)
	}
	return uhwc
}

// SetUpdatedAt sets the "updated_at" field.
func (uhwc *UserHomeWorkCreate) SetUpdatedAt(t time.Time) *UserHomeWorkCreate {
	uhwc.mutation.SetUpdatedAt(t)
	return uhwc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uhwc *UserHomeWorkCreate) SetNillableUpdatedAt(t *time.Time) *UserHomeWorkCreate {
	if t != nil {
		uhwc.SetUpdatedAt(*t)
	}
	return uhwc
}

// SetID sets the "id" field.
func (uhwc *UserHomeWorkCreate) SetID(u uint64) *UserHomeWorkCreate {
	uhwc.mutation.SetID(u)
	return uhwc
}

// Mutation returns the UserHomeWorkMutation object of the builder.
func (uhwc *UserHomeWorkCreate) Mutation() *UserHomeWorkMutation {
	return uhwc.mutation
}

// Save creates the UserHomeWork in the database.
func (uhwc *UserHomeWorkCreate) Save(ctx context.Context) (*UserHomeWork, error) {
	var (
		err  error
		node *UserHomeWork
	)
	uhwc.defaults()
	if len(uhwc.hooks) == 0 {
		if err = uhwc.check(); err != nil {
			return nil, err
		}
		node, err = uhwc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserHomeWorkMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uhwc.check(); err != nil {
				return nil, err
			}
			uhwc.mutation = mutation
			if node, err = uhwc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(uhwc.hooks) - 1; i >= 0; i-- {
			if uhwc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uhwc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, uhwc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*UserHomeWork)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from UserHomeWorkMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uhwc *UserHomeWorkCreate) SaveX(ctx context.Context) *UserHomeWork {
	v, err := uhwc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uhwc *UserHomeWorkCreate) Exec(ctx context.Context) error {
	_, err := uhwc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uhwc *UserHomeWorkCreate) ExecX(ctx context.Context) {
	if err := uhwc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uhwc *UserHomeWorkCreate) defaults() {
	if _, ok := uhwc.mutation.CreatedAt(); !ok {
		v := userhomework.DefaultCreatedAt()
		uhwc.mutation.SetCreatedAt(v)
	}
	if _, ok := uhwc.mutation.UpdatedAt(); !ok {
		v := userhomework.DefaultUpdatedAt()
		uhwc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uhwc *UserHomeWorkCreate) check() error {
	return nil
}

func (uhwc *UserHomeWorkCreate) sqlSave(ctx context.Context) (*UserHomeWork, error) {
	_node, _spec := uhwc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uhwc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	return _node, nil
}

func (uhwc *UserHomeWorkCreate) createSpec() (*UserHomeWork, *sqlgraph.CreateSpec) {
	var (
		_node = &UserHomeWork{config: uhwc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: userhomework.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: userhomework.FieldID,
			},
		}
	)
	if id, ok := uhwc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := uhwc.mutation.HomeworkID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: userhomework.FieldHomeworkID,
		})
		_node.HomeworkID = value
	}
	if value, ok := uhwc.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: userhomework.FieldUserID,
		})
		_node.UserID = value
	}
	if value, ok := uhwc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userhomework.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := uhwc.mutation.Content(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userhomework.FieldContent,
		})
		_node.Content = value
	}
	if value, ok := uhwc.mutation.Pics(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: userhomework.FieldPics,
		})
		_node.Pics = value
	}
	if value, ok := uhwc.mutation.Extra(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userhomework.FieldExtra,
		})
		_node.Extra = value
	}
	if value, ok := uhwc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userhomework.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := uhwc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userhomework.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// UserHomeWorkCreateBulk is the builder for creating many UserHomeWork entities in bulk.
type UserHomeWorkCreateBulk struct {
	config
	builders []*UserHomeWorkCreate
}

// Save creates the UserHomeWork entities in the database.
func (uhwcb *UserHomeWorkCreateBulk) Save(ctx context.Context) ([]*UserHomeWork, error) {
	specs := make([]*sqlgraph.CreateSpec, len(uhwcb.builders))
	nodes := make([]*UserHomeWork, len(uhwcb.builders))
	mutators := make([]Mutator, len(uhwcb.builders))
	for i := range uhwcb.builders {
		func(i int, root context.Context) {
			builder := uhwcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserHomeWorkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uhwcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uhwcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uhwcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uhwcb *UserHomeWorkCreateBulk) SaveX(ctx context.Context) []*UserHomeWork {
	v, err := uhwcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uhwcb *UserHomeWorkCreateBulk) Exec(ctx context.Context) error {
	_, err := uhwcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uhwcb *UserHomeWorkCreateBulk) ExecX(ctx context.Context) {
	if err := uhwcb.Exec(ctx); err != nil {
		panic(err)
	}
}
