// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"family-joint-school/mysql/ent/predicate"
	"family-joint-school/mysql/ent/userhomework"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserHomeWorkQuery is the builder for querying UserHomeWork entities.
type UserHomeWorkQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserHomeWork
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserHomeWorkQuery builder.
func (uhwq *UserHomeWorkQuery) Where(ps ...predicate.UserHomeWork) *UserHomeWorkQuery {
	uhwq.predicates = append(uhwq.predicates, ps...)
	return uhwq
}

// Limit adds a limit step to the query.
func (uhwq *UserHomeWorkQuery) Limit(limit int) *UserHomeWorkQuery {
	uhwq.limit = &limit
	return uhwq
}

// Offset adds an offset step to the query.
func (uhwq *UserHomeWorkQuery) Offset(offset int) *UserHomeWorkQuery {
	uhwq.offset = &offset
	return uhwq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uhwq *UserHomeWorkQuery) Unique(unique bool) *UserHomeWorkQuery {
	uhwq.unique = &unique
	return uhwq
}

// Order adds an order step to the query.
func (uhwq *UserHomeWorkQuery) Order(o ...OrderFunc) *UserHomeWorkQuery {
	uhwq.order = append(uhwq.order, o...)
	return uhwq
}

// First returns the first UserHomeWork entity from the query.
// Returns a *NotFoundError when no UserHomeWork was found.
func (uhwq *UserHomeWorkQuery) First(ctx context.Context) (*UserHomeWork, error) {
	nodes, err := uhwq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userhomework.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uhwq *UserHomeWorkQuery) FirstX(ctx context.Context) *UserHomeWork {
	node, err := uhwq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserHomeWork ID from the query.
// Returns a *NotFoundError when no UserHomeWork ID was found.
func (uhwq *UserHomeWorkQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = uhwq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userhomework.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uhwq *UserHomeWorkQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := uhwq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserHomeWork entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserHomeWork entity is found.
// Returns a *NotFoundError when no UserHomeWork entities are found.
func (uhwq *UserHomeWorkQuery) Only(ctx context.Context) (*UserHomeWork, error) {
	nodes, err := uhwq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userhomework.Label}
	default:
		return nil, &NotSingularError{userhomework.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uhwq *UserHomeWorkQuery) OnlyX(ctx context.Context) *UserHomeWork {
	node, err := uhwq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserHomeWork ID in the query.
// Returns a *NotSingularError when more than one UserHomeWork ID is found.
// Returns a *NotFoundError when no entities are found.
func (uhwq *UserHomeWorkQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = uhwq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userhomework.Label}
	default:
		err = &NotSingularError{userhomework.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uhwq *UserHomeWorkQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := uhwq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserHomeWorks.
func (uhwq *UserHomeWorkQuery) All(ctx context.Context) ([]*UserHomeWork, error) {
	if err := uhwq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uhwq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uhwq *UserHomeWorkQuery) AllX(ctx context.Context) []*UserHomeWork {
	nodes, err := uhwq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserHomeWork IDs.
func (uhwq *UserHomeWorkQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := uhwq.Select(userhomework.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uhwq *UserHomeWorkQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := uhwq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uhwq *UserHomeWorkQuery) Count(ctx context.Context) (int, error) {
	if err := uhwq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uhwq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uhwq *UserHomeWorkQuery) CountX(ctx context.Context) int {
	count, err := uhwq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uhwq *UserHomeWorkQuery) Exist(ctx context.Context) (bool, error) {
	if err := uhwq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uhwq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uhwq *UserHomeWorkQuery) ExistX(ctx context.Context) bool {
	exist, err := uhwq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserHomeWorkQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uhwq *UserHomeWorkQuery) Clone() *UserHomeWorkQuery {
	if uhwq == nil {
		return nil
	}
	return &UserHomeWorkQuery{
		config:     uhwq.config,
		limit:      uhwq.limit,
		offset:     uhwq.offset,
		order:      append([]OrderFunc{}, uhwq.order...),
		predicates: append([]predicate.UserHomeWork{}, uhwq.predicates...),
		// clone intermediate query.
		sql:    uhwq.sql.Clone(),
		path:   uhwq.path,
		unique: uhwq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		HomeworkID uint64 `json:"homework_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserHomeWork.Query().
//		GroupBy(userhomework.FieldHomeworkID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (uhwq *UserHomeWorkQuery) GroupBy(field string, fields ...string) *UserHomeWorkGroupBy {
	grbuild := &UserHomeWorkGroupBy{config: uhwq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uhwq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uhwq.sqlQuery(ctx), nil
	}
	grbuild.label = userhomework.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		HomeworkID uint64 `json:"homework_id,omitempty"`
//	}
//
//	client.UserHomeWork.Query().
//		Select(userhomework.FieldHomeworkID).
//		Scan(ctx, &v)
//
func (uhwq *UserHomeWorkQuery) Select(fields ...string) *UserHomeWorkSelect {
	uhwq.fields = append(uhwq.fields, fields...)
	selbuild := &UserHomeWorkSelect{UserHomeWorkQuery: uhwq}
	selbuild.label = userhomework.Label
	selbuild.flds, selbuild.scan = &uhwq.fields, selbuild.Scan
	return selbuild
}

func (uhwq *UserHomeWorkQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uhwq.fields {
		if !userhomework.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uhwq.path != nil {
		prev, err := uhwq.path(ctx)
		if err != nil {
			return err
		}
		uhwq.sql = prev
	}
	return nil
}

func (uhwq *UserHomeWorkQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserHomeWork, error) {
	var (
		nodes = []*UserHomeWork{}
		_spec = uhwq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*UserHomeWork).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &UserHomeWork{config: uhwq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uhwq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uhwq *UserHomeWorkQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uhwq.querySpec()
	_spec.Node.Columns = uhwq.fields
	if len(uhwq.fields) > 0 {
		_spec.Unique = uhwq.unique != nil && *uhwq.unique
	}
	return sqlgraph.CountNodes(ctx, uhwq.driver, _spec)
}

func (uhwq *UserHomeWorkQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := uhwq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (uhwq *UserHomeWorkQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userhomework.Table,
			Columns: userhomework.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: userhomework.FieldID,
			},
		},
		From:   uhwq.sql,
		Unique: true,
	}
	if unique := uhwq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uhwq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userhomework.FieldID)
		for i := range fields {
			if fields[i] != userhomework.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uhwq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uhwq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uhwq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uhwq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uhwq *UserHomeWorkQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uhwq.driver.Dialect())
	t1 := builder.Table(userhomework.Table)
	columns := uhwq.fields
	if len(columns) == 0 {
		columns = userhomework.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uhwq.sql != nil {
		selector = uhwq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uhwq.unique != nil && *uhwq.unique {
		selector.Distinct()
	}
	for _, p := range uhwq.predicates {
		p(selector)
	}
	for _, p := range uhwq.order {
		p(selector)
	}
	if offset := uhwq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uhwq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserHomeWorkGroupBy is the group-by builder for UserHomeWork entities.
type UserHomeWorkGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uhwgb *UserHomeWorkGroupBy) Aggregate(fns ...AggregateFunc) *UserHomeWorkGroupBy {
	uhwgb.fns = append(uhwgb.fns, fns...)
	return uhwgb
}

// Scan applies the group-by query and scans the result into the given value.
func (uhwgb *UserHomeWorkGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := uhwgb.path(ctx)
	if err != nil {
		return err
	}
	uhwgb.sql = query
	return uhwgb.sqlScan(ctx, v)
}

func (uhwgb *UserHomeWorkGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range uhwgb.fields {
		if !userhomework.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uhwgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uhwgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uhwgb *UserHomeWorkGroupBy) sqlQuery() *sql.Selector {
	selector := uhwgb.sql.Select()
	aggregation := make([]string, 0, len(uhwgb.fns))
	for _, fn := range uhwgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(uhwgb.fields)+len(uhwgb.fns))
		for _, f := range uhwgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(uhwgb.fields...)...)
}

// UserHomeWorkSelect is the builder for selecting fields of UserHomeWork entities.
type UserHomeWorkSelect struct {
	*UserHomeWorkQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uhws *UserHomeWorkSelect) Scan(ctx context.Context, v interface{}) error {
	if err := uhws.prepareQuery(ctx); err != nil {
		return err
	}
	uhws.sql = uhws.UserHomeWorkQuery.sqlQuery(ctx)
	return uhws.sqlScan(ctx, v)
}

func (uhws *UserHomeWorkSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uhws.sql.Query()
	if err := uhws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
