// Code generated by ent, DO NOT EDIT.

package userhomework

import (
	"time"
)

const (
	// Label holds the string label denoting the userhomework type in the database.
	Label = "user_home_work"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHomeworkID holds the string denoting the homework_id field in the database.
	FieldHomeworkID = "homework_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldPics holds the string denoting the pics field in the database.
	FieldPics = "pics"
	// FieldExtra holds the string denoting the extra field in the database.
	FieldExtra = "extra"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the userhomework in the database.
	Table = "stu_homework"
)

// Columns holds all SQL columns for userhomework fields.
var Columns = []string{
	FieldID,
	FieldHomeworkID,
	FieldUserID,
	FieldTitle,
	FieldContent,
	FieldPics,
	FieldExtra,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
